name: SonarCloud Analysis

on:
  push:
    branches:
      - main  
jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Cache SonarCloud packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: Install SonarScanner
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre-headless
        npm install -g sonarqube-scanner

    - name: SonarCloud Scan
      run: sonar-scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}