query ordersAvailableToReturn($filter: ReturnRequestFilters, $page: Int!) {
  ordersAvailableToReturn(filter: $filter, page: $page) 
  @context(provider: "vtexromania.return-app-sellers") {
    list {
      orderId
      creationDate
      invoicedItems {
        id
        productId
        quantity
      }
      processedItems {
        itemIndex
        quantity
      }
      excludedItems {
        itemIndex
      }
    }
    paging {
      total
      pages
      currentPage
      perPage
    }
  }
}
