#import './returnDetailsFragment.gql'

query getRequestDetails($requestId: ID!) {
  returnRequestDetails: returnRequest(requestId: $requestId)
    @context(provider: "vtexromania.return-app-sellers") {
    ...ReturnDetailsAdminFragment
  }
}
