name: Build
on:
 push:
   branches:
     - main
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: |
          cd node
          yarn
      - name: Test and coverage
        run: |
          cd node 
          yarn test --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
          with:
          args: >
            -Dsonar.projectKey=return-app-sellers \
            -Dsonar.organization=itglobers \
            -Dsonar.sources=./node \
            -Dsonar.exclusions=./node/__tests__/**/*,./**/__tests__/* \
            -Dsonar.tests=./node/__tests__/**/*,./node/__tests__/* \
            -Dsonar.javascript.lcov.reportPaths=./node/coverage/lcov.info \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}            